name: Test
on:
  push: {}

jobs:
  go_test:
    name: Go Test
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.0' # The Go version to download (if necessary) and use.
      - run: go version
      - run: |
         cd go
         go test -v

  java_test:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variables
        run: |
          echo "runner_arch=$(uname -m)" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: docker context create builders
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          endpoint: builders
      - name: Cache Docker Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: "${{ runner.os }}-${{ env.runner_arch }}-buildx-java-${{ github.sha }}"
          restore-keys: "${{ runner.os }}-${{ env.runner_arch }}-buildx-java-"
      - run: ls -al && echo ========== && echo ls -al java
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: java/
          file: java/build.Dockerfile
          push: false
          tags: local/temp:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
